### ISSUE TITLE
Blank lines with spaces in the decompiled source

### ISSUE THREAD

**Issue by Machine-Maker** [Vineflower/vineflower#359] opened 2024-04-07 04:40 UTC
## Vineflower version
1.11.0-20240406.040032-5

## Describe the bug
Some files seem to have spaces on blank lines.

## Additional information
There are tons of examples, you can just do a fresh decompile of Minecraft and to a regex search for lines that only contain spaces. This is an example from `net.minecraft.data.recipes.RecipeProvider`.

```java
private static final Map<BlockFamily.Variant, BiFunction<ItemLike, ItemLike, RecipeBuilder>> SHAPE_BUILDERS = ImmutableMap.<BlockFamily.Variant, BiFunction<ItemLike, ItemLike, RecipeBuilder>>builder(
            // spaces until here on L50
        )
        .put(BlockFamily.Variant.BUTTON, (output, input) -> {
            return buttonBuilder(output, Ingredient.of(input));
        })
```

**Comment by jaskarth** [comment] 2024-04-08 22:54
Fixed by #362, thank you for the report!

**Comment by Machine-Maker** [comment] 2024-04-08 23:48
I guess it technically fixed the one I listed in the issue, but there are still tons of other cases of extra spaces on blank lines. I'll open a new report with as many cases as I can find that seem different.

**Comment by jaskarth** [comment] 2024-04-08 23:49
I think it'll be okay to re-use this one. I'll reopen it, feel free to add the new cases here.

**Comment by Machine-Maker** [comment] 2024-04-08 23:50
Well actually, intellij has this handy export findings to txt file. So [here](https://pastes.dev/hpuTWbkQ1D) is all of the offenders in the mc source. I searched for `^\s\s\s\s*$`.

**Comment by jpenilla** [comment] 2024-04-09 01:19
This test case reproduces the issue:
```java
   static {
      takeLambda00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000(// 13
         () -> {
            for (int i = 0; i < 10; i++) {// 14
               System.out.println(i);// 15
            }
   
            if (new Random().nextBoolean()) {// 17
               System.out.println(true);// 18
            }
         }// 20
      );
   }// 21

  static void takeLambda00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000(Runnable r) {
  }
```

The issue is basically that the lambda argument's indent is being appended to blank lines in the lambda.

**Closed** 2024-04-16 15:33 UTC
Labels: bug, Subsystem: Writing, Priority: Medium
