### ISSUE TITLE
$VF: Couldn't be decompiled

### ISSUE THREAD

**Issue by bisguard** [Vineflower/vineflower#412] opened 2024-08-14 19:50 UTC
## Vineflower version
vineflower-1.10.1.jar.

## Describe the bug
Couldn't decompile because org\joda\time\format\DateTimeFormatterBuilder.java:1262: error: unclosed character literal var1.append('ï¿½');.

## Additional information
When decompiled log5j-1.1-joda-1.5.2.jar
StackTrace:
// $VF: Couldn't be decompiled
// Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
// java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "keyField" is null
//   at org.jetbrains.java.decompiler.main.ClassesProcessor.processClass(ClassesProcessor.java:439)
//   at org.jetbrains.java.decompiler.main.Fernflower.processClass(Fernflower.java:183)
//   at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$2(ContextUnit.java:164)
// Caused by: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "keyField" is null
//   at org.jetbrains.java.decompiler.main.rels.NestedClassProcessor.getMaskLocalVars(NestedClassProcessor.java:747)
//   at org.jetbrains.java.decompiler.main.rels.NestedClassProcessor.computeLocalVarsAndDefinitions(NestedClassProcessor.java:338)
//   at org.jetbrains.java.decompiler.main.rels.NestedClassProcessor.processClass(NestedClassProcessor.java:67)
//   at org.jetbrains.java.decompiler.main.ClassesProcessor.processClass(ClassesProcessor.java:431)
//   at org.jetbrains.java.decompiler.main.Fernflower.processClass(Fernflower.java:183)
//   at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$2(ContextUnit.java:164)

**Comment by Geolykt** [comment] 2024-08-14 19:52
I'm slightly confused how the "Decribe the bug" section correlates with the stacktrace provided.

**Comment by sschr15** [comment] 2024-08-15 04:01
The "describe the bug" section seems to indicate some failure of recompilation due to a UTF-8 encoding issue (it's interpreting u+FFFD as three characters instead of a UTF-8 sequence).

However, I can reproduce the error itself with [log5j-1.1-joda-1.5.2.jar](https://sourceforge.net/projects/log5j/files/log5j/log5j-1_1/log5j-1.1-joda-1.5.2.jar/download) from Sourceforge. It comes when decompiling `org.joda.time.chrono.GJChronology`.

**Comment by bisguard** [comment] 2024-08-15 04:43
Great, but JD-GUI, FernFlower, Procyon, and CFR decompile this class successfully

**Comment by jaskarth** [comment] 2024-08-16 17:49
Fixed in [36db2f6](https://github.com/Vineflower/vineflower/commit/36db2f6d85aef9359185bdec6cae8fa9f52fa9b2). Thanks for the report!

**Closed by jaskarth** 2024-08-16 17:49 UTC
Labels: bug, Subsystem: Writing, Priority: Medium
